# Generated by Django 6.0.2 on 2026-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefundDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('flight_type', models.CharField(max_length=50)),
                ('ticket_type', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('accepted_alternative', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('airline_name', models.CharField(blank=True, default='', max_length=100)),
                ('flight_number', models.CharField(blank=True, default='', max_length=20)),
                ('flight_date', models.CharField(blank=True, default='', max_length=20)),
                ('flight_duration_hours', models.FloatField(blank=True, null=True)),
                ('delay_hours', models.FloatField(blank=True, null=True)),
                ('bag_delay_hours', models.FloatField(blank=True, null=True)),
                ('ticket_price', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PARTIAL', 'Partial'), ('ERROR', 'Error')], max_length=10)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('analysis_steps', models.JSONField(default=list)),
                ('reasons', models.JSONField(default=list)),
                ('applicable_regulations', models.JSONField(default=list)),
                ('refund_details', models.JSONField(blank=True, null=True)),
                ('passenger_action_items', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('decision_letter', models.TextField(blank=True, default='')),
                ('raw_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
