# Generated by Django 6.0.2 on 2026-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunddecision',
            name='decision_letter',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
