# Generated by Django 6.0.3 on 2026-03-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_alter_refunddecision_decision_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='refunddecision',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='decisions.tenant'),
        ),
        migrations.AddIndex(
            model_name='refunddecision',
            index=models.Index(fields=['tenant', '-created_at'], name='decisions_r_tenant__f31356_idx'),
        ),
    ]
