# Generated by Django 6.0.3 on 2026-03-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_tenant_and_refunddecision_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('building', 'Building'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='building', max_length=20)),
                ('doc_count', models.PositiveIntegerField(default=0)),
                ('doc_manifest', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='refunddecision',
            name='index_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='decisions.indexversion'),
        ),
    ]
